export const UPLOAD_STATUS = {
    IDLE: 0,
    UPLOADING: 1,
    SUCCESS: 2,
    ERROR: 3,
};

export const MENU_STEPS = {
    CROP: "Crop",
    EDIT: "Edit",
    UPLOAD_POST: "Upload Post",
    CREATE_POST: "Create Post",
    EDIT_AVATAR: "Edit Avatar",
};

export const FILTER_VALUES = {
    "filter-1977": "sepia(.5) hue-rotate(-30deg) saturate(1.4)",
    "filter-aden": "sepia(.2) brightness(1.15) saturate(1.4)",
    "filter-amaro": "sepia(.35) contrast(1.1) brightness(1.2) saturate(1.3)",
    "filter-ashby": "sepia(.5) contrast(1.2) saturate(1.8)",
    "filter-brannan": "sepia(.4) contrast(1.25) brightness(1.1) saturate(.9) hue-rotate(-2deg)",
    "filter-brooklyn": "sepia(.25) contrast(1.25) brightness(1.25) hue-rotate(5deg)",
    "filter-charmes": "sepia(.25) contrast(1.25) brightness(1.25) saturate(1.35) hue-rotate(-5deg)",
    "filter-clarendon": "sepia(.15) contrast(1.25) brightness(1.25) hue-rotate(5deg)",
    "filter-crema": "sepia(.5) contrast(1.25) brightness(1.15) saturate(.9) hue-rotate(-2deg)",
    "filter-dogpatch": "sepia(.35) saturate(1.1) contrast(1.5)",
    "filter-earlybird": "sepia(.25) contrast(1.25) brightness(1.15) saturate(.9) hue-rotate(-5deg)",
    "filter-gingham": "contrast(1.1) brightness(1.1)",
    "filter-ginza": "sepia(.25) contrast(1.15) brightness(1.2) saturate(1.35) hue-rotate(-5deg)",
    "filter-hafe": "sepia(.4) contrast(1.5) brightness(1.2) saturate(1.4) hue-rotate(-10deg)",
    "filter-helena": "sepia(.5) contrast(1.05) brightness(1.05) saturate(1.35)",
    "filter-hudson": "sepia(.25) contrast(1.2) brightness(1.2) saturate(1.05) hue-rotate(-15deg)",
    "filter-inkwell": "brightness(1.25) contrast(.85) grayscale(1)",
    "filter-kelvin": "sepia(.15) contrast(1.5) brightness(1.1) hue-rotate(-10deg)",
    "filter-lark": "sepia(.25) contrast(1.2) brightness(1.3) saturate(1.25)",
    "filter-lofi": "saturate(1.1) contrast(1.5)",
    "filter-ludwig": "sepia(.25) contrast(1.05) brightness(1.05) saturate(2)",
    "filter-maven": "sepia(.35) contrast(1.05) brightness(1.05) saturate(1.75)",
    "filter-mayfair": "contrast(1.1) brightness(1.15) saturate(1.1)",
    "filter-moon": "brightness(1.4) contrast(.95) saturate(0) sepia(.35)",
    "filter-nashville": "sepia(.25) contrast(1.5) brightness(.9) hue-rotate(-15deg)",
    "filter-perpetua": "contrast(1.1) brightness(1.25) saturate(1.1)",
    "filter-poprocket": "sepia(.15) brightness(1.2)",
    "filter-reyes": "sepia(.75) contrast(.75) brightness(1.25) saturate(1.4)",
    "filter-rise": "sepia(.25) contrast(1.25) brightness(1.2) saturate(.9)",
    "filter-sierra": "sepia(.25) contrast(1.5) brightness(.9) hue-rotate(-15deg)",
    "filter-skyline": "sepia(.15) contrast(1.25) brightness(1.25) saturate(1.2)",
    "filter-slumber": "sepia(.35) contrast(1.25) saturate(1.25)",
    "filter-stinson": "sepia(.35) contrast(1.25) brightness(1.1) saturate(1.25)",
    "filter-sutro": "sepia(.4) contrast(1.2) brightness(.9) saturate(1.4) hue-rotate(-10deg)",
    "filter-toaster": "sepia(.25) contrast(1.5) brightness(.95) hue-rotate(-15deg)",
    "filter-valencia": "sepia(.25) contrast(1.1) brightness(1.1)",
    "filter-vesper": "sepia(.35) contrast(1.15) brightness(1.2) saturate(1.3)",
    "filter-walden": "sepia(.35) contrast(.8) brightness(1.25) saturate(1.4)",
    "filter-willow": "brightness(1.2) contrast(.85) saturate(.05) sepia(.2)",
    "filter-xpro-ii": "sepia(.45) contrast(1.25) brightness(1.75) saturate(1.3) hue-rotate(-5deg)",
};
